service: url-shortener

useDotenv: true

frameworkVersion: '2'

custom:
  bucketName: migueli.to

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: dev
  environment:
    BUCKET_NAME: "${self:custom.bucketName}"
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

package:
  include:
    - src/api.py
    - src/validators.py
  exclude:
    - '**/*'

functions:
  shorten:
    handler: src/api.handle
    events:
      - http:
          path: /
          method: post

resources:
  Resources:
    ServerlessRedirectS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    ServerlessRedirectS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.bucketName}
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: "Allow"
              Resource:
                - arn:aws:s3:::${self:custom.bucketName}/*
              Principal: "*"
