Resources:
  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Links-${self:provider.stage}
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: backhalf
          AttributeType: S
      KeySchema:
        - AttributeName: backhalf
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: User-index
          KeySchema:
            - AttributeName: user
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
