Resources: 
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [IsPro, "${self:custom.rootDomain}", "dev.${self:custom.rootDomain}"]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  WebBucket:
    Type: AWS::S3::Bucket
    Condition: IsPro
    Properties:
      BucketName: "${self:custom.rootDomain}-web"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsPro
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: RedirectBucketOrigin
            DomainName: !Select [1, !Split ["://", !GetAtt RedirectBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
          - Id: WebBucketOrigin
            DomainName: !Select [1, !Split ["://", !GetAtt WebBucket.WebsiteURL]]
            OriginPath: /dist
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        CustomErrorResponses:
          - ErrorCode: '404'
            ResponsePagePath: "/404.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
        Aliases:
          - ${self:custom.rootDomain}
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: ${self:custom.certificateArn}
          SslSupportMethod: sni-only
        CacheBehaviors:
          - PathPattern: '*.html'
            TargetOriginId: WebBucketOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              QueryString: false
          - PathPattern: '*.css'
            TargetOriginId: WebBucketOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              QueryString: false
          - PathPattern: '*.js'
            TargetOriginId: WebBucketOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              QueryString: false
        DefaultCacheBehavior:
          TargetOriginId: RedirectBucketOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
          DefaultTTL: 30
          ForwardedValues:
            QueryString: false