name: test

on: push

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  PY_COLORS: 1

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      - name: Run tests
        run: make unit-test

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install Serverless Framework
        run: npm i -g serverless@2.38.0

      - name: Run tests
        run: make integration-test
