name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run tests
        run: make test

      - name: Output the test report
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: testResults

